### ISSUE TITLE
JMBayes2 results don't seem to match JMBayes results

### ISSUE THREAD

**Issue by jpkrooney** [drizopoulos/JMbayes2#1]
Hi Dimirtris,
Great to see this new package. I was just testing it out and I found that results from JMBayes and JMBayes2 don't match when the same sub-models are used as arguments.

A reprex:
`library(JMbayes)`
`lmeFit.aids <- lme(CD4 ~ obstime * drug, random = ~ obstime | patient, data = aids)`
`survFit.aids <- coxph(Surv(Time, death) ~ drug, data = aids.id, x = TRUE)`
`JMB1_model  <- jointModelBayes(lmeFit.aids, survFit.aids, timeVar = "obstime")`
`library(JMbayes2)`
`JMB2_model <- jm(survFit.aids, lmeFit.aids, time_var = "obstime")`

Looking at the results:
<img width="616" alt="Screenshot 2021-01-14 at 13 29 10" src="https://user-images.githubusercontent.com/41968663/104591279-bb136800-566c-11eb-8961-a6fe0e8d7161.png">

<img width="651" alt="Screenshot 2021-01-14 at 13 33 47" src="https://user-images.githubusercontent.com/41968663/104591665-4db40700-566d-11eb-8ed5-22ed78819e40.png">

As you can see the results are quite different. I note that some that there are less parameters in JMBayes2, so perhaps I should not expect the same results ? However in my own data the AssocT parameter changed from a significant negative number to a significant positive number so I thought this issue was worth raising.
Many thanks!

**Comment by harryparr** [comment]
Hi - I'm also having similar issues that my alpha value (and other event) parameters are in opposing directions between JMBayes2 and `JMBayes::jointModelBayes` & `mvjointModelBayes`

**Comment by drizopoulos** [comment]
JMbayes2 implements a better MCMC algorithm than JMbayes. In particular, it uses the hierarchical centering parameterization and also center covariates in both submodels. In addition, JMbayes2 uses three chains compared to the single chain of JMbayes. In that way, we can assess convergence better using, e.g., the German-Rubin diagnostic (i.e., Rhat values in the results). In this example, the Rhat values indicate successful convergence. Hence, all in all, the results from JMbayes2 are more trustworthy.

**Comment by drizopoulos** [comment]
But in any case, thanks for reporting. We will investigate this further...

**Comment by jpkrooney** [comment]
Thanks Dimitris that is great. The updates in JMB2 are great and so far it seems much faster to me!

Maybe it helpful to give the issue some real world context ?:

In ALS most (2/3) die from respiratory failure and in this paper (https://hrbopenresearch.org/articles/2-23 ) we are using a longitudinal metric of respiratory function such that lower scores => worse respiratory function. I reran one of the models from the paper in original JMBayes and in JMBayes2:

```
lme_ref <- lme(SNIP.occ ~ ns(onset2snip_mnths, 2) ,
               random = ~ ns(onset2snip_mnths, 2)  | ID,
               data = df.snip_72m)

coxC9 <- coxph(Surv(time = dx_delay, time2 = surv_t2_months, fail) ~ age_on +
                   dx_delay2 + simp_site + C9,
               data = df.clin_72m, x = TRUE, model = TRUE)

JMB1_mod <- jointModelBayes(lme_ref, coxC9, timeVar = "onset2snip_mnths",
                             verbose = FALSE)
library(JMbayes2)
JMB2_mod <- jm(coxC9, lme_ref, time_var = "onset2snip_mnths")
```
Here are the Event process results from both:
<img width="715" alt="Screenshot 2021-01-14 at 17 45 07" src="https://user-images.githubusercontent.com/41968663/104621417-61249980-5690-11eb-81ec-2f7054506bb8.png">

As you can see the AssocT term has flipped sign in the JMB2 model. So this would then imply that decreased respiratory function is associated with improved survival -> which doesn't make sense given background knowledge.

**Comment by drizopoulos** [comment]
Thanks for the additional info. Would it be possible to try fitting with jm() again by altering the prior for the tau_bs_gammas. Namely using the following

jm(..., priors = list(A_tau_bs_gammas = 1, B_tau_bs_gammas = 0.01))

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by jpkrooney** [comment]
Yes no problem! I just fit this:
```
JMB2_mod2 <- jm(coxC9, lme_ref, time_var = "onset2snip_mnths",
                priors = list(A_tau_bs_gammas = 1, B_tau_bs_gammas = 0.01))

```
And the results are not much different than the default priors:

<img width="660" alt="Screenshot 2021-01-14 at 19 12 40" src="https://user-images.githubusercontent.com/41968663/104631403-7dc6ce80-569c-11eb-92a6-e403097d46f8.png">

**Comment by drizopoulos** [comment]
I just pushed a new version (JMbayes2_0.1-3) on GitHub - could you try with this one.

**Comment by jpkrooney** [comment]
Hi Dimitris - I just ran the models again after updating. They are in much closer agreement now between JMBayes original, JMBayes2 and JMBayes2 with the tweaked priors:

<img width="729" alt="Screenshot 2021-01-15 at 00 46 56" src="https://user-images.githubusercontent.com/41968663/104662701-afa35980-56cb-11eb-89b7-360cd3aed4b0.png">

If I understand your code tweaks properly, this was something to do with the position of spline knots for the baseline hazards ?

**Comment by drizopoulos** [comment]
Yes, indeed. I had changed the default position of the knots to improve convergence, but apparently this was not a great idea. Thanks for the feedback.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by jpkrooney** [comment]
Thats good to know - thanks for looking into this so quickly!
