### ISSUE TITLE
issuses about predictive accuracy & dynamic prediction applications

### ISSUE THREAD

**Issue by oorun123** [drizopoulos/JMbayes2#101]
Dear Professor Dimitris Rizopoulos,
The multi-model dynamic predictions you have developed using super learning algorithms are really great! Still, I would like to implement ways to evaluate this super model with ROC curves (AUC values), calibration curves, etc. Also, I am very much looking forward to your development of an adapted Shiny interface to implement the functionality of the web calculator. 
Thanks again for your work in developing such a great predictive model！
Best regards!

**Comment by drizopoulos** [comment]
Thanks for this feature request. We plan to add this.

**Comment by FangLiu-Github** [comment]
> Thanks for this feature request. We plan to add this.

Dear Professor Dimitris Rizopoulos,
Where should it be added? Where can we find it?
Thanks for your work！
Best regards!
