### ISSUE TITLE
Nested / multilevel random-effects query

### ISSUE THREAD

**Issue by harryparr** [drizopoulos/JMbayes2#11]
Dear Prof Rizopoulos,

Is it possible that the `lme` can handle multiple sources of a multi-level/nested random effect model, say not only individuals but also between different studies? 

When I try to specify the mixed-effects model via `lme` I can either use the `||` notation or say `random = list(Study= ~ 1, USUBJID = ~ ns(Time,2)))`. When I go to fit the `jm`, I receive the error 
`Error in mat[id, ] <- b : 
  number of items to replace is not a multiple of replacement length`  (fitting with only the individual ID term is fine)

I assume the `jm` function cannot handle nested random-effects at this time. What would you advise, keeping the `Study` variable as a main effect only in the `lme` and/or using some strata/cluster/frailty term in the survival submodel? 

Many thanks,
Harry

**Comment by drizopoulos** [comment]
Indeed, nested random-effects structures are not yet supported in **JMbayes2**.

**Comment by Djennifer** [comment]
Given that this issue was addressed some time ago, I am curious about the current developments regarding nested random-effects structures in JMbayes2. To my knowledge, this feature has not yet been implemented. Could you provide any insights into whether this is planned for future updates?

**Comment by drizopoulos** [comment]
It is planned for future updates, but it is not certain yet when it will be ready.
