### ISSUE TITLE
Error when running 'predict()' according to the example in competing risk vignette

### ISSUE THREAD

**Issue by mikoSL** [drizopoulos/JMbayes2#12]
Thank you for the great [work/article](https://drizopoulos.github.io/JMbayes2/articles/Competing_Risks.html) published on 2021-12-19. 

When running the example according to this article,

```
predLong <- predict(jFit_CR, newdata = ND, return_newdata = TRUE,
                    times = seq(6.5, 15, length = 25))
predEvent <- predict(jFit_CR, newdata = ND, return_newdata = TRUE,
                     process = "event")
```

It shows **Error in split.default(x, g) : first argument must be a vector**

According to the [discussion](https://github.com/drizopoulos/JMbayes/issues/39) in JMbayes, performing dynamic predictions from a competing risk `mvJMbayes` object is not supported, I am very excited that it is implemented in JMbayes2, it would be so wonderful to run through the example code and apply it with other data later.

BTW,  JMbayes2 version I used is 0.1.8.
Thank you very much for your time.

**Comment by drizopoulos** [comment]
Is this with the most recent version from GitHub, i.e., JMbayes2_0.1-85?

**Comment by mikoSL** [comment]
It is same with [this issue](https://github.com/drizopoulos/JMbayes2/issues/13).
Close it and follow the discussion of [this issue](https://github.com/drizopoulos/JMbayes2/issues/13).

**Comment by mikoSL** [comment]
Thank you very much for the hint. 

I have installed the latest version from Github, 
in Rstudio, with packageVersion('JMbayes2'), it shows 0.1-85. 

When run jm(), 
```
jFit_CR <- jm(CoxFit_CR, list(fm1, fm2), time_var = "year", 
              functional_forms = CR_forms, 
              n_iter = 25000L, n_burnin = 5000L, n_thin = 5L)
```

It shows the following error:
```
OMP: Error #13: Assertion failure at kmp_csupport.cpp(492).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.

OMP: Error #13: Assertion failure at kmp_csupport.cpp(492).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
Error in unserialize(node$con) : error reading from connection
```
@Rochelle1995, what is your result?

**Comment by Rochelle1995** [comment]
installed too, and runs without any problem on mine..However, I noticed something. In the cumulative risk part of the plot, it is not clear which event the curves belong to. I think a legend can solve this problem. Thanks...

**Comment by drizopoulos** [comment]
I cannot reproduce this error. I guess it has to do with your installation of Rcpp and RcppArmadillo.

**Comment by mikoSL** [comment]
> 

@Rochelle1995 
I checked all [commits](https://github.com/drizopoulos/JMbayes2/commits/master), 
then found the commit on Dec  17th,2021 was the change for version 0.1-85, 
I installed with `remotes::install_github("drizopoulos/JMbayes2@8d6f6f86eafc847a1dfd0b75fe6e2768b5192063")`
But due to the error I had, there might be a better way to install the latest version in github. 

Could you please share how you installed it?

**Comment by Rochelle1995** [comment]
I didn't do anything different.  I followed the commands on the site.  I just didn't have rtools installed, r asked for it, I installed..

**Comment by mikoSL** [comment]
It was the problem of gfortran, fixed it according to [this link](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/). 
Now the code runs successfully. Thank you all for help!
