### ISSUE TITLE
Error in predict function in JMbayes2 

### ISSUE THREAD

**Issue by Rochelle1995** [drizopoulos/JMbayes2#13]
Thank you , Here is the error

  predLong <- predict(jFit_CR, newdata = ND, return_newdata = TRUE,    times = seq(6.5, 15, length = 25))
Error in split.default(x, g) : first argument must be a vector

predEvent <- predict(jFit_CR, newdata = ND, return_newdata = TRUE, process = "event")
Error in split.default(x, g) : first argument must be a vector

**Comment by drizopoulos** [comment]
Is this with the most recent version from GitHub, i.e., JMbayes2_0.1-85?

**Comment by Rochelle1995** [comment]
No, it is 0.1.80 from CRAN
