### ISSUE TITLE
Sum of cumulative risk more than one for dynamic prediction.

### ISSUE THREAD

**Issue by anorvik** [drizopoulos/JMbayes2#14]
Hello!
I have tried to experiment with your newly added dynamic prediction for competing risks and have results I do not understand. When extending time of prediction to 25 in the example provided the sum of cumulative risk adds up to more than one.
Here is the code I use:
predLong <- predict(jFit_CR, newdata = ND, return_newdata = TRUE, times = seq(6.5, 25, length = 25))
predEvent <- predict(jFit_CR, newdata = ND, return_newdata = TRUE, process = "event", times = seq(6.5, 25, length = 25))
plot(predLong, predEvent, outcomes = 1:2, pos_ylab_long = c(0.1, 20))

sessioninfo: 
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

other attached packages:
[1] JMbayes2_0.2-0     GLMMadaptive_0.8-2 nlme_3.1-151       survival_3.1-12 

Best regards
Anders Norvik

**Comment by drizopoulos** [comment]
Thanks for reporting this. There was a problem with the code. The current GitHub version should resolve this.
