### ISSUE TITLE
jm iteration progress bar

### ISSUE THREAD

**Issue by harryparr** [drizopoulos/JMbayes2#18]
Is there scope to add a progress bar on the fitting of `jm`, as there was within `JMbayes::jointModelBayes(..., control=list(verbose=TRUE))`, or a way to do this on the fly or see/print how many MCMC iterations have been performed at periodic intervals? 

Thanks, Harry

**Comment by drizopoulos** [comment]
We will need to look into that because the MCMC iterations are done in C++ and in parallel. Hence, it is not that straightforward.
