### ISSUE TITLE
survival  no events in the interval

### ISSUE THREAD

**Issue by antoine4ucsd** [drizopoulos/JMbayes2#20]
Hello
I am very interested in your package to look at biomarker(s) associated with death. I have a cohort of participants who all died after 50 and 360 days of follow-up. For those,I have ~50 markers with heterogeneity in sampling time.
I was able to run your joint model as described in https://drizopoulos.github.io/JMbayes2/articles/Dynamic_Predictions.html
but I fail running the survival analyses:
```
roc <- tvROC(jointFit, newdata = mydata, Tstart = t0, Dt = 60, cores = 1L)
```
where t0= 300 days (some participants died after 330-360 days) . I tried with multiple t0 and Dt... 

error message
rror in tvROC.jm(jointFit, newdata = marker_df_wide2, Tstart = t0, Dt = 60,  : 
  it seems that there are no events in the interval [Tstart, Thoriz).

I would be happy to share the data via mp if you are interested
thank you!

**Comment by drizopoulos** [comment]
Are there events between 330 and 360 days?

**Comment by antoine4ucsd** [comment]
yes. I can share the data via mp if it helps
see below

thank you!
<img width="542" alt="Screen Shot 2022-03-17 at 1 40 35 PM" src="https://user-images.githubusercontent.com/18502631/158891609-765fa3e1-6a60-45e1-b6b5-8f0eee5eb3a6.png">

**Comment by drizopoulos** [comment]
And did these subjects also have repeated measurements before 330 days?

**Comment by antoine4ucsd** [comment]
some do.
for example for id1:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/18502631/158894584-1955deb0-71fb-482f-9181-18c6009585aa.png">

**Comment by drizopoulos** [comment]
In the data.frame you provide in the newdata argument, all subjects need to have at least one longitudinal measurement before the Tstart time.

**Comment by antoine4ucsd** [comment]
still not working... 
if newdata is ID 5 only
<img width="266" alt="image" src="https://user-images.githubusercontent.com/18502631/158898400-5db740ab-15f2-4379-957d-9df7c844a272.png">

and t0=300
I tried
roc <- tvROC(jointFit, newdata = marker_df_wide_pid5, Tstart = t0, Dt = 47, cores = 1L)
or 
roc <- tvROC(jointFit, newdata = marker_df_wide_pid5, Tstart = t0, Dt = 347, cores = 1L)

this is probably obvious...sorry

**Comment by antoine4ucsd** [comment]
I tihnk this mighjt be because all my individuals died so event should be 1 in every cells. I thought it had to be 1 only at the time of event.

I also have this error for survival
```

ND <- marker_df_wide[marker_df_wide$id %in% c(5,12), ] # I exclude those with < 90 days follow up and only 1 tp after filtering
ND
t0 <- 90 # all selected individuals were alived at day 90

ND <- ND[ND$day < t0, ]
ND
t0
ND$status2 <- 0 # were alive up to this time point
ND$days <- t0
View(ND)
predLong1 <- predict(jointFit, newdata = ND, return_newdata = TRUE)

predLong2 <- predict(jointFit, newdata = ND,
                     times = seq(t0, 346, length.out = 51),
                     return_newdata = TRUE)


predSurv <- predict(jointFit, newdata = ND, process = "event",
+                     times = seq(t0, 346, length.out = 51),
+                     return_newdata = TRUE)
```
Error in t.default(st0) : argument is not a matrix

N after filering is below
id5 was followed until 346 days and id 12 followed until day 247

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/18502631/158915123-1217af02-6f42-4e0f-94b9-5721350db22b.png">



all suggestions and/or alternative approaches are welcome. happy to chat more via mp or call.
THANK YOU!

**Comment by drizopoulos** [comment]
Please arrange your data as in the example in the vignette.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by antoine4ucsd** [comment]
Did you see something obviously wrong in my data? I guess I missed something…

--
a





From: Dimitris Rizopoulos ***@***.***>
Date: Thursday, March 17, 2022 at 8:14 PM
To: drizopoulos/JMbayes2 ***@***.***>
Cc: antoine ***@***.***>, Author ***@***.***>
Subject: Re: [drizopoulos/JMbayes2] survival no events in the interval (Issue #20)
Please arrange your data as in the example in the vignette.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by drizopoulos** [comment]
What is the syntax you used to fit the joint model?

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
