### ISSUE TITLE
Can not install the Package ("JMbayes")

### ISSUE THREAD

**Issue by OceansDeep219** [drizopoulos/JMbayes2#21]
Unable to install the package("JMbayes") in R 4.1.3 on Mac OS 12.3 or Win 11.
Error: package or namespace load failed for 'jmbayes': When '**rjags**' is counted in loadnamespace() Onload failed.

**Comment by drizopoulos** [comment]
This is the repository for the JMbayes2 package which is a newer version than JMbayes. Try `install.packages("JMbayes2")`.

**Comment by OceansDeep219** [comment]
Thanks for your reply,  i have installed the package "### JMbayes2",  but i can not use the **jointModelBayes(...)** function. Could you teach me how to use the functions in the ### Packages: jointModelBayes

**Comment by drizopoulos** [comment]
There are several examples on the website of the package: [https://drizopoulos.github.io/JMbayes2/](https://drizopoulos.github.io/JMbayes2/).

**Comment by OceansDeep219** [comment]
I see, thank you very much! ^-^!
