### ISSUE TITLE
question: interval censored outcomes?

### ISSUE THREAD

**Issue by bcjaeger** [drizopoulos/JMbayes2#27]
Hi @drizopoulos!

This software is incredible. Thank you for developing it.  `JMbayes` allows users to pass models for interval-censored outcomes fit with `survreg` into the joint model fitting function. Does `JMbayes2` allow this? I apologize if this is stated in the documentation somewhere and I missed it.

**Comment by bcjaeger** [comment]
Great! Are there any examples or vignettes with code for this?

**Comment by drizopoulos** [comment]
Unfortunately, not yet.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by bcjaeger** [comment]
No problem. Thank you for checking! I have a reprex below where I am trying to get an interval-censored model to run with `jm`, but an error seems to occur during the cpp routine. Can you review this and let me know if there is a modification I can make to get the interval-censored model right? 

``` r
library(JMbayes2)
#> Loading required package: survival
#> Loading required package: nlme
#> Loading required package: GLMMadaptive
#> Loading required package: splines
library(tidyverse)

pbc2_id_intervals <- pbc2.id %>% 
 transmute(
  id, 
  years,
  status2,
  drug,
  # pretend death was interval censored
  t1 = years,
  t2 = if_else(status2 == 1, years + abs(rnorm(n())), Inf),
 )

# coxph fit
fit_surv_coxph <- coxph(Surv(years, status2) ~ drug, 
                        data = pbc2_id_intervals)

# interval censoring fit
fit_surv_intervals <- survreg(
 formula =  Surv(t1, t2, type = "interval2") ~ drug,
 data = pbc2_id_intervals,
 model = TRUE
)

# longitudinal model for bili
fit_lme <- lme(fixed = log(serBilir) ~ year * sex + I(year^2) +
                age + prothrombin, random =  ~ year | id, data = pbc2)

joint_model_fit_coxph <- jm(Surv_object = fit_surv_coxph, 
                            Mixed_objects = fit_lme, 
                            time_var = "year",
                            n_chains = 1L, 
                            n_iter = 11000L, 
                            n_burnin = 1000L)

joint_model_fit_intervals <- jm(Surv_object = fit_surv_intervals, 
                                Mixed_objects = fit_lme, 
                                time_var = "year",
                                n_chains = 1L, 
                                n_iter = 11000L, 
                                n_burnin = 1000L)
#> Error in checkForRemoteErrors(val): one node produced an error: matrix multiplication: incompatible matrix dimensions: 4680x1 and 2x1
```

<sup>Created on 2022-07-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bcjaeger** [comment]
Hi @drizopoulos, I apologize for rushing a response, but do you have any recommendations based on the example above?

**Comment by drizopoulos** [comment]
Sorry, I didn't have the time to look into this yet.

**Comment by Minana05** [comment]
Hi, @bcjaeger. I met a very similar problem today while running the joint model. Did you solve your problem? Thanks!

**Comment by bcjaeger** [comment]
Hi! I haven't figured out a solution in `JMbayes2` yet. If you are in a hurry, you may be able to fit your interval-censored models using `JMbayes`.

**Comment by drizopoulos** [comment]
It should work with `Surv(..., type = "interval")`.

**Comment by bcjaeger** [comment]
That works! Thank you. I'm pasting the update below in case it is helpful to others:

```r

fit_surv_intervals <- survreg(
 formula =  Surv(t1, t2, status2, type = "interval") ~ drug,
 data = pbc2_id_intervals,
 model = TRUE
)

```
