### ISSUE TITLE
Error when save_random_effect = TRUE and missing longitudinal data

### ISSUE THREAD

**Issue by AdamMS** [drizopoulos/JMbayes2#28]
First of all... JMBayes2 is awesome.  Thank you!  It is really useful!

Issue:
If some subjects have no data for the longitudinal response, I can still fit a model in JMBayes2.
However, if I also specify save_random_effects = TRUE, then jm() returns the following error (see MWE below):

Error in dim(x) <- sapply(dnames_b, length) : 
  dims [product 1555] do not match the length of object [1560]

To create a MWE, I modified the code from the competing risks vignette (https://drizopoulos.github.io/JMbayes2/articles/Competing_Risks.html) by replacing longitudinal responses for Subject 1 with NA.  Then, in the longitudinal models, I set na.action to na.exclude.

pb_exclude <- pbc2 %>% mutate(prothrombin = replace(prothrombin, id == 1, NA),
                              serBilir = replace(serBilir, id == 1, NA))

fm1_exclude <- lme(log(serBilir) ~ poly(year, 2) * drug, 
                   data = pb_exclude, 
                   random = ~ poly(year, 2) | id,
                   na.action = na.exclude)
fm2_exclude <- lme(prothrombin ~ year * drug, 
                   data = pb_exclude, 
                   random = ~ year | id,
                   na.action = na.exclude)

jFit_CR <- jm(CoxFit_CR, list(fm1_exclude, fm2_exclude), time_var = "year", 
              functional_forms = CR_forms,
              control = list(n_iter = 250L,
                             n_burnin = 150L,
                             n_thin = 1L,
                             save_random_effects = TRUE))

Note: the model fits fine if save_random_effects = FALSE.

**Comment by drizopoulos** [comment]
Thanks for reporting; it should be solved now.
