### ISSUE TITLE
tvROC output

### ISSUE THREAD

**Issue by harryparr** [drizopoulos/JMbayes2#29]
This is a question on the interpretation of the output of the `tvROC` function in the [dynamic predictions vignette](https://drizopoulos.github.io/JMbayes2/articles/Dynamic_Predictions.html#predictive-accuracy). In the example the ROC output presents cut-offs, sensitivity, specificity, along with some other accuracy metrics. 

In this example, those metrics are given for each cut-off threshold. In row 39, the asterisk indicates the optimal Youden index, i.e., giving equal weight to both sensitivity & specificity and maximising them both. What is the interpretation here, that the 'optimal' cut-off which maximises the model's discriminative ability to maximise true-positives and minimise false-negatives, is a risk threshold of 0.73 using longitudinal information up to 5 years, predicting at 8 years? Additionally, this cut-off column is the probability of event risk threshold and not the biomarker - is this correct? 

Can you also explain the interpretation of the qSN, qSP, and qOverall indexes? 

Thank you

**Comment by drizopoulos** [comment]
Yes, this is correct. The quantities qSN and qSP are the quality sensitivity and specificity. I had a paper describing those, but I cannot easily find it now.
