### ISSUE TITLE
Extracting log-likelihood

### ISSUE THREAD

**Issue by AdamMS** [drizopoulos/JMbayes2#30]
The help document for "jm" says that an object of class "jm" will contain log-likelihood (conditional and marginal) for posterior samples.  So, for example, for a fitted model named 'JMfit', the components JMfit$logLik and JMfit$mlogLik will contain the posterior likelihoods.

When I run the competing risks model from the vignette, the log-likelihoods are not part of the output.

Is there a way to retrieve the posterior log-likelihoods?

**Comment by drizopoulos** [comment]
You can find the fit statistics in the `fit_stats` component of a fitted model object. We will update the documentation to state the correct information.
