### ISSUE TITLE
LONGITUDINAL PROCESS AND RECURRENT PROCESS ASSOCIATION STRUCTURE

### ISSUE THREAD

**Issue by caterinagregorio** [drizopoulos/JMbayes2#34]
Does the package allow to add in the longitudinal part of the model the shared frailty of the recurrent event process? 
Thank you

**Comment by drizopoulos** [comment]
The current version does not allow this.

**Comment by drizopoulos** [comment]
No this is not possible.

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Caterina Gregorio ***@***.***>
Στάλθηκε: Thursday, July 21, 2022 7:09:04 PM
Προς: drizopoulos/JMbayes2 ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: [drizopoulos/JMbayes2] LONGITUDINAL PROCESS AND RECURRENT PROCESS ASSOCIATION STRUCTURE (Issue #34)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Does the package allow to add in the longitudinal part of the model the shared frailty of the recurrent event process?
Thank you
