### ISSUE TITLE
jm() with only random intercept possible?

### ISSUE THREAD

**Issue by egenbrugge** [drizopoulos/JMbayes2#36]
Dear Dimitris Rizopoulos,

I have noticed that mixed_model() with only a random intercept returns an error: jm() does not currently work when you have a single longitudinal outcome and only random intercepts. 

However, in the jm() function there is the argument zero_ind: a list with integer vectors indicating which coefficients are set to zero in the calculation of the value term. This can be used to include for example only the random intercept; default is NULL.

Could you give an example of how to include only the random intercept term?

Many thanks in advance.

Kind regards,

Els

**Comment by drizopoulos** [comment]
Unfortunately, you cannot run `jm()` with a single random effect. For design purposes, we took the decision not to allow this case. Hence, you can try including an additional random effect.
