### ISSUE TITLE
Difference in estimates from longitudinal model for mixed_model() and output jm()

### ISSUE THREAD

**Issue by egenbrugge** [drizopoulos/JMbayes2#37]
Dear Dimitris Rizopoulos,

I have noticed that the estimates for the longitudinal model fitted with mixed_model() are different from the ones in the output after jm(). 

Example from the reference manual:

```

# [1] Fit the mixed model using lme().
fm1 <- lme(fixed = log(serBilir) ~ year * sex + I(year^2) +
             age + prothrombin, random = ~ year | id, data = pbc2)
summary(fm1)

# [2] Fit a Cox model, specifying the baseline covariates to be included in the
# joint model.
fCox1 <- coxph(Surv(years, status2) ~ drug + age, data = pbc2.id)
# [3] The basic joint model is fitted using a call to jm() i.e.,
joint_model_fit_1 <- jm(fCox1, fm1, time_var = "year",
                        n_chains = 1L, n_iter = 11000L, n_burnin = 1000L
                        )
summary(joint_model_fit_1)

```

Questions:

1. I am assuming this difference is due to the frequentist versus Bayesian nature of the models. Which model estimates should I report? The ones from mixed_model() or the longitudinal outcome from the  jm() output?
2. In the aforementioned example the estimates from both models are quite similar but in the model I am working on they differ wildly. For example I get an intercept of -7.85 with mixed_model() - which did converge-  but an intercept of 102.35 in the output of the longitudinal outcome after fitting the joint model with jm(). Something similar happens for the effect of time. Could this be because the joint model did not converge and which possible approaches to take in that case? Or could this be due to something else? 

I tried to keep my example as short as possible but I can of course provide more details. It's more a general question about the differences in estimates than my example per se. 

Kind regards,

Els

**Comment by drizopoulos** [comment]
Yes, that would indicate that the joint model has not converged. Try increasing the number of iterations or simplifying the model.
