### ISSUE TITLE
Question / Issue: Calculating conditional longitudinal predictions (when some subjects have missing data)

### ISSUE THREAD

**Issue by AdamMS** [drizopoulos/JMbayes2#38]
Thank you in advance!

Context: 

- I want to produce mean posterior residuals for the longitudinal response.
- Conditional predictions using predict() do not match those I hand-calculate using: y^{pred} = X\beta + Zb
- For some subjects, my longitudinal data table only has a missing value for the response.  This is because some subjects have no data after baseline, and baseline is a predictor variable.  I do not know whether this is complicating issues, but I mention it in case.

Problem:

Predictions from predict() do not match predictions that I hand-calculate as: y^{pred} = X\beta + Zb, where I am using the mean posterior estimates for b.  I know that predict() is drawing from MCMC samples, but I think this approach should be okay for my purpose (finding mean posterior residuals).  Am I missing something?
     While I wonder whether predict() is correctly calculating predicted values, I have reached my limit in R coding as I try to trace the difference in methods.
     I should note that the problem with my actual data/model is more extreme than in the attached MWE.

Other Issue:

Am I using the correct technique to fit the model given the missing responses?
- I prep the data by taking all responses (including baseline), and then I replaced baseline responses with NAs.
- In fitting the lme() submodel, I use na.action = na.exclude
- This ensures that all subjects (with their predictors) appear in the longitudinal dataset, even though some have no observed longitudinal responses.

Again, thank you for your response.

MWE (R script saved as .txt):
[MWE_predict.txt](https://github.com/drizopoulos/JMbayes2/files/9382734/MWE_predict.txt)

**Comment by drizopoulos** [comment]
The `predict()` function is supposed to work for new datasets. If you want to calculate the fitted values, you will need to do the calculation by extracting the X and Z design matrices from the fitted object, and multiplying with the posterior means of beta and b.

**Comment by AdamMS** [comment]
I finally figured out how go get fitted values from predict().  The solution was suggested to me by the competing risks vignette, but it was not obvious.

- If I use the original longitudinal data for newdataL
- And I alter newdataE by: (i) changing all final statuses to zero (no event), and (ii) changing the time variable to zero
- Then the outputs appear to be fitted values
