### ISSUE TITLE
Missing values and NaN's not allowed if 'na.rm' is FALSE

### ISSUE THREAD

**Issue by Minana05** [drizopoulos/JMbayes2#39]
I tried to run the joint model with package "JMbayes2" and it returned this error "missing values and NaN's not allowed if 'na.rm' is FALSE
Calls: jm ... summary.mcmc.list -> t -> apply -> FUN -> quantile.default
Execution halted". 
But I do not have any missing value in my data set. I also tried other datasets and they run well. I was wondering what will hit the error without having missing data. Thank you so much!

**Comment by drizopoulos** [comment]
This error message indicates that there are missing data in the MCMC samples after the model is fitted. This could be caused by fitting an overly complicated model. But in any case, we will rectify it for the next release of the package.
