### ISSUE TITLE
ordinal and continuous time-dependent covariates with survival outcome in the same joint model

### ISSUE THREAD

**Issue by ElsaVazquez29** [drizopoulos/JMbayes2#40]
Hi @drizopoulos

Thank you for constantly continuing with the development of the JMbayes2 package. It has been extremely useful for my work. 

I was wondering if there is a way to fit joint models for survival outcomes where one longitudinal outcome is ordinal and the others are either continuous and binomial? This without having to use the expanded dataset created to fit the continuation ratio model for the ordinal outcome when fitting the models for the other longitudinal outcomes. I tried that and get an error stating that the same version of the dataset has to be used for each of the longitudinal sub models. 

Also, when I fit the joint model with a continuation ratio for the ordinal outcome I get the following error. 

_**Error in mlogLik_jm(res_thetas, statistics$Mean[["b"]], statistics$post_vars,  : 
  log_det_sympd(): given matrix is not symmetric positive ### definite**

Is there a way to correct for this error from either the mixed_model or the jm functions?

Any advice on this would be greatly apprecited.

**Comment by drizopoulos** [comment]
Thanks for reporting this. We are aware of the issue of fitting a joint model with an ordinal longitudinal outcome, and we will try to fix it soon. However, this is only for the case you have one ordinal longitudinal outcome. The case of combining multiple longitudinal outcomes with some of them being ordinal is more challenging to handle, and it will take some time to accommodate.
