### ISSUE TITLE
Error in checkForRemoteErrors(val) :   19 nodes produced errors

### ISSUE THREAD

**Issue by Minana05** [drizopoulos/JMbayes2#42]
I am trying to fit the joint model with a large dataset with more than 130k datalines and I met the following error:
Error in checkForRemoteErrors(val) :
  19 nodes produced errors; first error: addition: incompatible matrix dimensions: 18620x1 and 20501x1
Calls: jm ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted

Do you know how I can solve the problem? Thank you so much!

**Comment by drizopoulos** [comment]
I cannot reproduce this error. Perhaps it has to do with missing observations.

**Comment by Minana05** [comment]
Hi @drizopoulos , thank you so much for your response! I have found out the reason that induced this error and now the problem has been solved.
