### ISSUE TITLE
Request: Matrix inputs

### ISSUE THREAD

**Issue by AdamMS** [drizopoulos/JMbayes2#45]
The jm() function cannot handle matrix input variables, such as generated using splines.  It produces an error that the input dimensions do not match the dimensions of the object.

More specifically, consider three workflows using natural splines -- i.e., ns(variable, df):

1. Dataset -> Fit coxph and longitudinal models using ns(variable, df) in the formula -> Run jm()
2. Dataset -> Create spline variable using ns(variable, df) -> Fit coxph and longitudinal models using spline variable -> Run jm()
3. Dataset -> Create spline variable using ns(variable, df) -> Fit coxph and longitudinal models _without_ spline variable -> Run jm()

Workflow #1 runs just fine.
Workflow #2 returns multiple warnings about incorrect dimensions.
Workflow #3 also returns multiple warnings, in spite of the fact that the spline variable is not an input to the model.

Note: the lme() and coxph() submodels fit correctly.  It is just jm() that appears to have an indexing problem.

The following is a MWE:

```
# Cox model for the composite event death or transplantation
pbc2.id$status2 <- as.numeric(pbc2.id$status != 'alive')
CoxFit <- coxph(Surv(years, status2) ~ sex + ns(albumin, 2), data = pbc2.id)

# a linear mixed model for log serum bilirubin
fm1 <- lme(log(serBilir) ~ year * sex + ns(albumin, 2), data = pbc2, random = ~ year | id)

# the joint model that links all sub-models
jointFit <- jm(CoxFit, fm1, time_var = "year",
               n_iter = 500L, n_burnin = 200L, n_thin = 5L)



# Cox model for the composite event death or transplantation
newpbc2id <- pbc2.id
newpbc2id$albuminSpl <- ns(newpbc2id$albumin, 2)
CoxFit <- coxph(Surv(years, status2) ~ sex + albuminSpl, data = newpbc2id)

# a linear mixed model for log serum bilirubin
newpbc <- pbc2
newpbc$albuminSpl <- ns(newpbc$albumin, 2)
fm1 <- lme(log(serBilir) ~ year * sex + albuminSpl, data = newpbc, random = ~ year | id)

# the joint model that links all sub-models
jointFit <- jm(CoxFit, fm1, time_var = "year",
               n_iter = 500L, n_burnin = 200L, n_thin = 5L)



# Cox model for the composite event death or transplantation
CoxFit <- coxph(Surv(years, status2) ~ sex, data = newpbc2id)

# a linear mixed model for log serum bilirubin
fm1 <- lme(log(serBilir) ~ year * sex, data = newpbc, random = ~ year | id)

# the joint model that links all sub-models
jointFit <- jm(CoxFit, fm1, time_var = "year",
               n_iter = 500L, n_burnin = 200L, n_thin = 5L)
```

**Comment by drizopoulos** [comment]
This is a design decision within the package. The variables in a data frame cannot be a matrix. The consideration of splines should be done within the formula environment.

(To my knowledge, this is the safer choice, in general, in R).
