### ISSUE TITLE
what does pos_ylab_long mean ?

### ISSUE THREAD

**Issue by waybo-zz** [drizopoulos/JMbayes2#46]
I try to control the position of the y-axis labels in the middle of the two y-axis, however, I don't know the parameters mean. I tried lots of different numbers, and it doesn't work.  

Could you tell me what number should I use?  

outcome 1: values limits 20 -100

outcome 2: values limits 0.2 - 10

Thanks very much

**Comment by waybo-zz** [comment]
I think there might be a bug in it. 

I changed the line in plot.predict_jm function from

"pp <- par("usr")[1] + pos_ylab_long * diff(par("usr")[1:2])"

to

"pp <- par("usr")[3] + pos_ylab_long * diff(par("usr")[3:4])"

And it works

**Comment by drizopoulos** [comment]
I think you are correct. Thanks for proposing this patch. I will implement the change in the next version.
