### ISSUE TITLE
Heterogeneous Longitudinal Residuals

### ISSUE THREAD

**Issue by AdamMS** [drizopoulos/JMbayes2#50]
Does JMBayes2 accommodate heterogeneous residual variance in the longitudinal model? -- e.g. residuals are larger for men than for women.  I am implementing this in nlme::lme() as follows:

> weights = varIdent(form = ~ 1 | Sex)

If JMBayes2 does accommodate them, where do I find the posterior estimates of the group-specific variance terms in the model output?

Thank you

**Comment by drizopoulos** [comment]
This is currently not possible.

**Comment by AdamMS** [comment]
Thank you for the information.
