### ISSUE TITLE
question JMbayes2 package 

### ISSUE THREAD

**Issue by amirabadiza921** [drizopoulos/JMbayes2#51]
Hi drizopoulos
Should the JMbayes2 package have two longitudinal  variables?
The following codes, will their output be wrong?
modelcox<- coxph(Surv(f.time,ckd)~gender+age+tg+fbs,data=data.wide,model=T)
fil.lm<-lme(TSH~time,random=~time|id,data=dataLong)
ffm<-list("TSH"=~value(TSH)+slope(TSH))
fit.jm<-jm(modelcox,fit.lm,functional_forms=ffm,time_var="time",n_iter=10000)

thanks

**Comment by drizopoulos** [comment]
Sorry, but I do not understand the question.

**Comment by amirabadiza921** [comment]
> Sorry, but I do not understand the question.

Is the model I have implemented correct?
Because I only have a mixed effects model.
 package JMbayes2 only to allow models with more than one random effect.

**Comment by drizopoulos** [comment]
Indeed, in JMbayes2 you need to have more than one random effects.
