### ISSUE TITLE
Question: Identifiability of Wlong_std_alphas and W_std_gammas

### ISSUE THREAD

**Issue by AdamMS** [drizopoulos/JMbayes2#52]
If I understand correctly, the log-hazard function at time t is:
     log Hazard(t) = Association Effects at t + Baseline log Hazard at t + Survival Effects at t

As I understand the model outputs, both the association effects and the baseline hazard are modeled with a centering term:
* Association Effect (t) = LongResponse(t) * (U(t) %*% alphas) - **Wlong_std_alphas**
* Baseline log Hazard (t) = W0_H(t) %*% bs_gammas - **W_std_gammas**

Both of these centering terms are constants in the model.

My question is: how are Wlong_std_alphas and W_std_gammas made to be identifiable in estimation?

I understand that they have separate interpretations:
* W_std_gammas is essentially an intercept term for the baseline hazard spline
* Wlong_std_alphas "zeros out" the association effects so that they do not interfere with W_std_gammas

**Comment by drizopoulos** [comment]
To improve the mixing and convergence of the MCMC algorithm, we work with standardized design matrices in the survival submodel. However, by doing that, we also affect the estimation of the baseline hazard function. The components `Wlong_std_alphas` and `W_std_gammas` are used to rescale the baseline hazard.

**Comment by AdamMS** [comment]
Right.  I understand that (though not as concisely as you).  But I still don't understand how identifiability is achieved.  At a guess, I would say it's solely through the priors.

**Comment by drizopoulos** [comment]
I don't see any identifiability issues.

**Comment by AdamMS** [comment]
Perhaps I misunderstand how Wlong_std_alphas and W_std_gammas are employed in the equation for the log hazard?

I wrote a shorthand version of the log-hazard function in my original post, so maybe that will point the way to the source of my confusion --- but to cut straight to the point, I have (for a given subject):

log Hazard (t) = <Model Terms> - Wlong_std_alphas - W_std_gammas

where both Wlong_std_alphas are W_std_gammas are constants with respect to time, subject, and all other model parameters and predictors.

If I am correct on the hazard function, I do not see how the model can identify the contribution of Wlong_std_alphas separate from that of W_std_gammas.

**Comment by drizopoulos** [comment]
These objects are not involved in the estimation. Are only used afterwards to rescale back the baseline hazard. It is the same as running a regression model with standardized covariates and then you transform back the coefficients to the ones you had obtained if you hadn’t standardized.

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Adam Martin-Schwarze ***@***.***>
Στάλθηκε: Wednesday, February 8, 2023 1:33:15 AM
Προς: drizopoulos/JMbayes2 ***@***.***>
Κοιν.: Dimitris Rizopoulos ***@***.***>; Comment ***@***.***>
Θέμα: Re: [drizopoulos/JMbayes2] Question: Identifiability of Wlong_std_alphas and W_std_gammas (Issue #52)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Perhaps I misunderstand how Wlong_std_alphas and W_std_gammas are employed in the equation for the log hazard?

I wrote a shorthand version of the log-hazard function in my original post, so maybe that will point the way to the source of my confusion --- but to cut straight to the point, I have (for a given subject):

log Hazard (t) = - Wlong_std_alphas - W_std_gammas

where both Wlong_std_alphas are W_std_gammas are constants with respect to time, subject, and all other model parameters and predictors.

If I am correct on the hazard function, I do not see how the model can identify the contribution of Wlong_std_alphas separate from that of W_std_gammas.

**Comment by AdamMS** [comment]
Thank you.  I think I understand.
