### ISSUE TITLE
Question: Survival likelihood contribution for delayed entry

### ISSUE THREAD

**Issue by jcgiardina** [drizopoulos/JMbayes2#55]
Thank you for such a great package -- it has been so helpful and easy to use!

I was hoping you could answer a quick question I had about how the package handles delayed entry. My naive assumption was that delayed entry is incorporated into the likelihood function by conditioning on surviving until the entry time given the random effects, so that for entry time $T_{i0}$, event/censor time $T_{i1}$, and censoring indicator $\delta_{i}$, the survival contribution to the likelihood function is: 
$$p(T_{i1},\delta_{i}|T_{i}^{*}>T_{i0},b_{i},\theta) = h(T_{i1}|b_{i},\theta)^{\delta_{i}}\frac{S(T_{i1}|b_{i},\theta)}{S(T_{i0}|b_{i},\theta)} = h(T_{i1}|b_{i},\theta)^{\delta_{i}}\exp{\left(-\int_{T_{i0}}^{T_{i1}}h(u|b_{i},\theta)du\right)}$$

In other work on delayed entry with joint models, however, I've noticed that the entire likelihood function is divided by the probability of surviving until the entry time, with numerator and denominator separately integrated over the random effects distribution (e.g., equation 5 in [Crowther et al.](https://doi.org/10.1002/sim.6779)), so that the likelihood function is:
$$L(\theta)=\frac{\int p(T_{i1},\delta_{i}|b_{i},\theta) p(y_{i}|b_{i},\theta) p(b_{i}|\theta) db_{i}}{\int S(T_{i0}|b_{i},\theta) p(b_{i}|\theta) db_{i}}$$

Do you know which approach JMbayes2 takes to delayed entry? I'm using the package in a current project, and I'm just hoping to confirm either way for when I write-up the manuscript. (And apologies if there's an obvious answer -- unfortunately I don't know C++ well enough to figure this out directly from the code.) Thank you again for a fantastic package!

**Comment by drizopoulos** [comment]
Under the Bayesian approach, we define the likelihood conditional on the random effects, whereas, under the frequentist approach, we integrate the random effects out. In **JMbayes2**, the former equation is used.
