### ISSUE TITLE
Progress of the fit

### ISSUE THREAD

**Issue by berithunsdieck** [drizopoulos/JMbayes2#58]
Is it possible to see the progress of the fitting of the joint model like the number of iterations? I'm thinking of something like the checkpoints in brms package.

**Comment by berithunsdieck** [comment]
@drizopoulos In other packages, it's done for example by using verbose=TRUE (see JMstateModel , https://github.com/LoicFerrer/JMstateModel ). For the JMbayes packages this feature was implemented as well. Do you have an idea to get this information as wel for jmbayes2?

**Comment by drizopoulos** [comment]
This isn't easy to do in **JMbayes2** because the computations are done in C++.
