### ISSUE TITLE
Dynamic predictions: longitudinal outcome axis scale issue.

### ISSUE THREAD

**Issue by RyanJField** [drizopoulos/JMbayes2#6]
Hi,

I have found a possible issue with the `plot.predict_jm()`, currently it uses the range of values from the predict function for the ylim values, however if I have a biomarker with a valid range from 1-50000 (or 1-11 on the log scale) and I use the log scale of that variable in the JM the `plot.predict_jm()` function produces the following graph:

![log](https://user-images.githubusercontent.com/57794045/133749322-e69c4709-8eee-454c-bf7d-b85d75d50e42.png)

Which is easy to interpret, however if I use `fun_long = exp`, to use the original biomarker scale I get the following plot in which the ylim makes the graph hard to interpret:
 
![exp](https://user-images.githubusercontent.com/57794045/133749347-264ae8bd-70e4-449d-bcdd-7be8869caeb9.png)

It would be good if you could override the ylim for the longitudinal model(s) by specifying a custom range so the graph looks like this:

![exp-fixed](https://user-images.githubusercontent.com/57794045/133749368-9c88f1e5-f7b6-4b21-8d92-cccb107b450e.png)

Many Thanks.

**Comment by drizopoulos** [comment]
I see your point, and I will add a `ylim` argument to allow for finer control. With that being said, the reason why I have done it like this is to show the biomarker levels for this patient compared to the other patients in the dataset.

**Comment by drizopoulos** [comment]
The `plot()` method for `predict_jm` objects has gained the argument `ylim_long_outcome_range` the defaults to `TRUE`. If set to `FALSE`, the `ylim` is set according to the value of the specific subject being plotted.

**Comment by waybo-zz** [comment]
I'am changed a little for the function plot.predict_jm


From 

 ry <-  r range(preds, low, upp, na.rm = TRUE) 

to

    ry1 =  range(preds, low, upp, na.rm = TRUE) 
    ry <-  range(ry1[1]*0.8,ry1[2]*1.2)   

And it looks much better to me.

**Comment by drizopoulos** [comment]
Thanks, I will try it.
