### ISSUE TITLE
Median survival computation

### ISSUE THREAD

**Issue by JulietteOrtholand** [drizopoulos/JMbayes2#61]
Hi,

I could not re-open issue #60, so I created a new one... I computed it manually using simulated data but I found almost 2 times what I expected... Could you please confirm the following:

By default, using a longitudinal function phi(t) and no covariate, your hazard function is hazard(t) = h_0(t)*exp(B*phi(t)), with h_0 modelled by gammas and B a fixed effect. Thus to get the median survival of the population using the patient with random effects equal to 0:  
1. I estimated the function h_0(t) which is a gamma function with 5 knots (by default) thanks to [BSspline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.BSpline.html). 
2. I get the hazard function with the different parameters extracted from the summary of the survival and longitudinal function fit. 
3. I computed a primitive of the hazard, noted H with [integrate.quad](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad.html#scipy.integrate.quad). 
4. I computed the survival function S(t) = exp(-H(t)) to get the value t that solves S(t) = 0.5. 

Note that I use all the mean values of the fixed effects and gammas.

**Comment by drizopoulos** [comment]
This does not really refer to an issue/problem with the package but to how to perform a specific calculation. I would suggest reading about the formulation of joint models, e.g., in the JSS paper for JMbayes, and seeing how you need to do this. 

I must add here that the internal computation of the baseline hazard is for the standardized covariates and longitudinal outcomes. You will need to transform it back as it is done [here](https://github.com/drizopoulos/JMbayes2/blob/2aa6563cbca10b8a79f55ccb7af29addb9ae0548/src/mcmc_fit.cpp#L1127).
