### ISSUE TITLE
[Question]: Is it possible to obtain dynamic predictions for a multivariate linear mixed model without survival

### ISSUE THREAD

**Issue by frbrz** [drizopoulos/JMbayes2#62]
Hi,

Thanks for the great package! I am interested in jointly modelling two longitudinal outcomes with a correlated random intercept / slope model. I do not have any survival outcome, so I am just interested in the longitudinal component. Is it possible to obtain dynamic predictions for such model?

The model I am using, which I fitted using `JMBayes` is:
```
library(JMBayes)
fit2 <- mvglmer(
  list(
    Y1~ TIME + BL1 + (TIME | PATNUM),
    Y2 ~ TIME + BL2 + (TIME | PATNUM)
  ), 
  data = train_df,
  families = list(gaussian, gaussian)
)
```
I have tried using `IndvPred_lme()` but it does not work. Is there a `JMBayes2` (or other) solution?

Many thanks for your help.
Francesco

**Comment by drizopoulos** [comment]
Unfortunately, no.

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: frbrz ***@***.***>
Στάλθηκε: Friday, June 9, 2023 4:14:45 PM
Προς: drizopoulos/JMbayes2 ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: [drizopoulos/JMbayes2] [Question]: Is it possible to obtain dynamic predictions for a multivariate linear mixed model without survival (Issue #62)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi,

Thanks for the great package! I am interested in jointly modelling two longitudinal outcomes with a correlated random intercept / slopes model. I do not have any survival outcome, so I am just interested in the longitudinal component. Is it possible to obtain dynamic predictions for such model?

The model I am using, and fitting using JMBayes is:

library(JMBayes)
fit2 <- mvglmer(
  list(
    Y1~ TIME + BL1 + (TIME | PATNUM),
    Y2 ~ TIME + BL2 + (TIME | PATNUM)
  ),
  data = train_df,
  families = list(gaussian, gaussian)
)


I have tried using IndvPred_lme() but it does not work. Is there a JMBayes2 (or other) solution?

Many thanks for your help.
Francesco
