### ISSUE TITLE
Ordinal longitudinal outcomes eg likert scores

### ISSUE THREAD

**Issue by jpkrooney** [drizopoulos/JMbayes2#65]
Hi Dimitris. I see that ordinal outcomes are in the list of possible longitudinal sub-models, but I can't find any examples for something like a likert score - i.e. an outcome variable that could take values such as: Strongly disagree / Disagree / Neither agree nor disagree / Agree / Strongly agree. Are joint models using such variables as longitudinal outcome able to be fit in JMbayes2?

**Comment by jpkrooney** [comment]
Ok I'll take a look! Thanks!

**Comment by drizopoulos** [comment]
You will need the Cox model using the counting process formulation, i.e., with the variables `start`, `stop`, and `event` and include the `cohort` variable as a time-varying covariate.  Then using the `functional_forms` argument of `jm()` you can include the interaction `value(y_new):cohort`.

**Comment by jpkrooney** [comment]
Ah. My longitudinal outcome variable doesn't exist in the event dataset for complicated reasons so it won't work. But I tried it using another variable simply as a test and it seemd to work ok
