### ISSUE TITLE
Models involving zero-inflated/hurdle distributions fail to stabilize

### ISSUE THREAD

**Issue by Esculab** [drizopoulos/JMbayes2#66]
Dear Dimitris

First, congrats for this amazing and flexible package, and all the doc and tutorials you provide on it!

I am not sure if the problem below is really a bug or just me not knowing exactly how to use and fine-tune the jm function.

From my experience, it seems longitudinal models involving zero-inflated/hurdle distributions have more trouble to make the joint model converge (more specifically, the "alphas" of the survival model). I always observed that at least one or more chains of the MCMC do not stabilize, whereas the same model without the zero-inflated/hurdle component almost always converges from the start. I have observed this for all distributions (Poisson, neg binomial, Beta…)

Increasing the number of iterations does not seem to solve the problem, chains keep showing large fluctuations (e.g. in ggtraceplot) 

So my questions: Is there a way to make ZI/hurdles models stabilize ? Also, what could explain that only these specific “two-part” models failed to stabilize and not their counterparts without the extra zeros component ?

Thanks for your time!

**Comment by drizopoulos** [comment]
Thanks for your nice words regarding our package!

Regarding your question, JMbayes2 does not currently work for models with excess zeros. Hence, fitting a zero-inflated/hurdle model with GLMMadaptive, and providing this as an argument to `jm()` will not fit a joint model with zero-inflated/hurdle. It will only use the non-zero part. This could explain the convergence issues you observe.

**Comment by Esculab** [comment]
Thanks for the fast reply! I suspected there would be a general explanation to this ;)
