### ISSUE TITLE
Changing functional_form completely changes the significance of Y in the survival part

### ISSUE THREAD

**Issue by Esculab** [drizopoulos/JMbayes2#67]
Dear Dimitris

I have fitted a joint model where the longitudinal predictor Y is modeled with `mixed_model `using the negative binomial distribution.
In the summary, the linear predictor` value(Y) `is clearly associated with the survival outcome. 

However, I wanted to have a more direct interpretation such as “_an increase of 1 in Y is associated with an increase if xx.x % of the risk_”, instead of having to rely on the linear predictor. I used the `functional_form `argument (in an `update `call) to force the survival part to use the longitudinal value in its original scale using the `vexp(value(Y))`.

The problem is that now, `vexp(value(Y))` is no longer associated with the survival outcome.
(I precise that both models have converged, looking at RHat and traceplots) Conditional DIC, WAIC and LPML, on the other hand, have completely blown up!

I tried to fit, in a more naive way, a separate Cox model using the subject_specific response from the same mixed_model, it remains clearly associated with the survival outcome, even with the original scale. (this remains true even if I select only one case per individual to avoid the repeated measurements)

I don’t know what causes this issue, but I clearly expect that this predictor associates with survival outcome (even in original scale).

I was able to reproduce this phenomenon with the following code (adapted from your website such that it is closer to my own data, it seems increasing `t_max `further accentuates this observation) 

Thanks in advance for any advice or hint on what is going wrong here !

```
set.seed(1234)
n <- 500 # number of subjects
K <- 10 # number of measurements per subject
t_max <- 15 # maximum follow-up time

DF <- data.frame(id = rep(seq_len(n), each = K),
                 time = c(replicate(n, c(0, sort(runif(K - 1, 0, t_max))))),
                 sex = rep(gl(2, n/2, labels = c("male", "female")), each = K))

X <- model.matrix(~ sex * time, data = DF)
Z <- model.matrix(~ time, data = DF)

betas <- c(0.0, -0.15, 0.2, -0.15) # fixed effects coefficients
shape <- 2 # shape/size parameter of the negative binomial distribution
D11 <- .250 # variance of random intercepts
D22 <- 0.03 # variance of random slopes

b <- cbind(rnorm(n, sd = sqrt(D11)), rnorm(n, sd = sqrt(D22)))

# linear predictor
eta_y <- as.vector(X %*% betas + rowSums(Z * b[DF$id, ]))
# mean of the Beta distribution
mu_y <- plogis(eta_y) # plogis(eta_y) = exp(eta_y) / (1 + exp(eta_y))
# we simulate negative binomial longitudinal data
DF$y <- rnbinom(n * K, size = shape, mu = exp(eta_y))

# simulate event times
upp_Cens <- 5 # fixed Type I censoring time
shape_wb <- 2 # shape Weibull
alpha <- 0.8 # association coefficient
gammas <- c("(Intercept)" = -5, "sex" = 0.2)
W <- model.matrix(~ sex, data = DF[!duplicated(DF$id), ])
# linear predictor for the survival model
eta_t <- as.vector(W %*% gammas)

invS <- function (t, i) {
  # i denotes the subject
  sex_i <- W[i, 2L]
  # h() is the hazard function and we assume a Weibull baseline hazard
  h <- function (s) {
    X_at_s <- cbind(1, sex_i, s, sex_i * s)
    Z_at_s <- cbind(1, s)
    # the linear predictor from the mixed model evaluated at time s
    f <- as.vector(X_at_s %*% betas +
                     rowSums(Z_at_s * b[rep(i, nrow(Z_at_s)), ]))
    exp(log(shape_wb) + (shape_wb - 1) * log(s) + eta_t[i] + f * alpha)
  }
  # -log(S(t)) = H(t), where H(t) is the cumulative hazard function
  integrate(h, lower = 0, upper = t)$value + log(u[i])
}
# we simulate the event times
u <- runif(n)
trueTimes <- numeric(n)
for (i in seq_len(n)) {
    Up <- 100
    Root <- try(uniroot(invS, interval = c(1e-05, Up), i = i)$root, TRUE)
    trueTimes[i] <- if (!inherits(Root, "try-error")) Root else 150
}


Ctimes <- upp_Cens
Time <- pmin(trueTimes, Ctimes)
event <- as.numeric(trueTimes <= Ctimes) # event indicator

# we keep the longitudinal measurements before the event times
DF$Time <- Time[DF$id]
DF$event <- event[DF$id]
DF <- DF[DF$time <= DF$Time, ]

DF_id <- DF[!duplicated(DF$id), ]

#Fitting the models
Cox_fit <- coxph(Surv(Time, event) ~1 , data = DF_id)
NB_MixMod <- mixed_model(y ~ time, random = ~ time | id, data = DF,
                         family = negative.binomial())

jointFit <- jm(Cox_fit, NB_MixMod, time_var = "time")
jointFit2<- update(jointFit, functional_forms = ~vexp(value(y)))

```
from the `summary` function of the two joint models:

```
#jointFit
Survival Outcome:
           Mean  StDev   2.5%  97.5% P   Rhat
value(y) 1.4594 0.3699 0.7963 2.2417 0 1.1506

#jointFit2
Survival Outcome:
                 Mean  StDev    2.5%  97.5%      P   Rhat
vexp(value(y)) 0.0108 0.0131 -0.0135 0.0406 0.3089 1.0054
```
However, using the predictions directly from the `predict` function (as below) in a Cox model,

```
predDF <- predict(jointFit, newdata = DF,process='longitudinal',type='subject_specific',type_pred='link',return_newdata = TRUE)
coxModel<- coxph(Surv(Time, event) ~exp(pred_y) , predDF )

```
gives the following association (this remains significant if I take only one measurement per id):
```

               coef exp(coef) se(coef)     z      p
exp(pred_y) 0.82076   2.27223  0.04812 17.05 <2e-16
```

I also noticed that the following calls do not give the same results, is it normal ?
```
predict(jointFit, newdata = DF,process='longitudinal',type='subject_specific',type_pred='response')
exp(predict(jointFit, newdata = DF,process='longitudinal',type='subject_specific',type_pred=’link’))

```

**Comment by drizopoulos** [comment]
In essence, you are fitting a misspecified model in this case. That is, the data have been simulated, assuming that the logarithm of the expected counts is associated with the hazard of the event, but the second model assumes an incorrect version of the longitudinal outcome variable. I would say that it is logical that this misspecification may affect the inference. 

Regarding the second question, the `predict()` method for joint models fitted with `jm()` calculates the expected value E(f(Xbeta + Zb_i)) wrt the distribution [b | T > t, Y_i(t)]. Hence, for `type_pred = 'response'` this is E(exp(Xbeta + Zb_i)), which is not equal to exp(E(Xbeta + Zb_i)) because the exponent is a nonlinear function.
