### ISSUE TITLE
How to calculate the risk as 1 unit change in SD for value, slope and area

### ISSUE THREAD

**Issue by liulinsmu** [drizopoulos/JMbayes2#68]
Dear Dimitris Rizopoulos,
I have difficulties in changing the scale of the predictors in ```jm()```. Specifically, I want to report the Hazard ratio of per 1 SD increase value.  

Here are some codes for your reference.
```
library(JMbayes2)
pbc2.id$status2 <- as.numeric(pbc2.id$status != 'alive')
CoxFit <- coxph(Surv(years, status2) ~ sex, data = pbc2.id)
fm1 <- lme(log(serBilir) ~ ns(year,2) , data = pbc2, random = ~ ns(year,2) | id)
jointFit1 <- jm(CoxFit, fm1, time_var = "year")
summary(jointFit1)
```

Then I can get the HR by ```exp(jointFit1[["statistics"]][["Mean"]][["alphas"]])```, which means the HR of per 1 unit incease ```value(log(serBilir))```.
However, how can I change the HR to per 1 SD increase?

In the general Cox regression model, I can get this by centering the predictor
```
model<- coxph(Surv(years, status2) ~ I(scale(serBilir)), data = pbc2.id)
summary(model)
```
I have read the document of ```JMbayes2``` but did not find the solution.
Any information is appreciated.

Thank you for your help

**Comment by drizopoulos** [comment]
The concept of standardizing a predictor becomes more tricky with longitudinal data because the standard deviation of a longitudinal outcome changes over time. Hence, you need to be careful of what exactly it means, if you use `scale(serBilir)`.

**Comment by liulinsmu** [comment]
Thank you for your prompt reply.

In my opinion, per 1 SD change of the biomarkers as the exposure is widely used in those biomarkers with a large value range (of course we can change it to per 10 units change or per 100 units change, etc.). Moreover, I think per 1 SD increase sometimes makes the risks of two different exposures comparable and more comprehensive.

Actually, my question originally came from [this article](https://www.jacc.org/doi/full/10.1016/j.jacc.2021.11.023), wherein the author investigated the relationship between both value, slope, and area of the biomarkers with the event, using ```JMbayes``` package. And they report the HR as per 1 SD change.

However, I tried to replicate their work but failed to convert the HR into per 1 SD change. I am not sure about the specific method they used so I am trying to ask for help here.

Thank you.

**Comment by drizopoulos** [comment]
You could try calculating the standard deviation of all longitudinal measurements and dividing by this number. This is for the value. If you want to do it for the slope, you need to the same but for the slope values calculated from the mixed effects model.

**Comment by liuyishuboo** [comment]
Dear liulinsmu,
The question you posed is very helpful to me。
Is there a solution to this problem? Can you please advise me on the exact method?
Thanks！
