### ISSUE TITLE
Weighted cumulative effects

### ISSUE THREAD

**Issue by FannyArtaud** [drizopoulos/JMbayes2#69]
Hello,

I'd like to use the method proposed in the paper "Extension of the Association structure in Joint Models to include Weighted Cumulative Effects" by Katya Mauffin et al.. Unfortunately, the code is adapted with the JMbayes package and not JMbayes2 and I'm not sure how to transcribe this code with the JMbayes2 package. Could you help me please?

The code with JMbayes is :
# NORMAL DISTRIBUTION SINGLE PARAMETER
wf <- function(u, parms, t.max)
num <- dnorm(x = u, sd = parms)
den <- pnorm(q = c(0, t.max), sd = parms)
num / (den[2L] - den[1L])
jointFit.strw_o <- update(jointFit.origREML, estimateWeightFun = TRUE,
weightFun = wf,
priorShapes = list(shape1 = dunif),
priors = list(priorshape1 = c(0, 5)))
summary(jointFit.strw_o)
plot(jointFit.strw_o, which = "weightFun", max.t = max(subset_surv$year_event))
plot(jointFit.strw_o)
# SKEWED NORMAL
wfsn <- function(u, parms, t.max)
num <- dst(x = u, omega = parms[1], alpha = parms[2])
den <- pst(x = c(0, t.max), omega = parms[1], alpha = parms[2])
num / (den[2L] - den[1L])
jointFitsn.strw_o <- update(jointFit.origREML, estimateWeightFun = TRUE,
weightFun = wfsn,
priorShapes = list(shape1 = dunif, shape2 = dunif),
priors = list(priorshape1 = c(0, 5),
priorshape2 = c(0, 10)))
summary(jointFitsn.strw_o)
plot(jointFitsn.strw_o, which = "weightFun", max.t = max(subset_surv$year_event))
plot(jointFitsn.strw_o)

In addition, I work on a population of 100,000 women, with 10% events and 400,000 visits. The models (even the simplest joint model) take more than 12h to run, do you know if it's possible to make them run faster? I tried with jm(... , , parallel = "multicore") but it didn't make any difference.

Thank you very much for your help and for your very intersting work !

Fanny

**Comment by drizopoulos** [comment]
This is not yet available in JMbayes2.

**Comment by drizopoulos** [comment]
Regarding the big dataset you can split it in smaller pieces, fit the model in each and then combine the results. Pedro has code to do that.
