### ISSUE TITLE
The AUC value of the joint model is smaller than that of the corresponding COX model

### ISSUE THREAD

**Issue by zhangkaicr** [drizopoulos/JMbayes2#72]
``I am a PhD student in oncology, and the dynamic prediction model you developed is very useful in clinical work. In routine medical research, the cox model is most commonly used. My research needs to compare the AUC value of the dynamic joint model with the AUC value of the traditional COX regression. I'm asking you for advice, I don't know if such a comparison can be made directly. The code below demonstrates my comparison process. Surprisingly, the AUC value of the joint model at some time points is actually lower than the traditional COX model.

Build a traditional cox model and calculate AUC values from 1 year to 5 years

`
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
CoxFit <- coxph(Surv(years, event ) ~ drug + age+ log(serBilir)+prothrombin+ascites, data = pbc2.id,x = T)

auc_cox <- 
  Score(list(CoxFit), 
        formula=Surv(years, status2)~1,
        data=pbc2.id, 
        metrics="auc", 
        null.model=FALSE, 
        times=seq(1:5))

auc_train_tab <- 
  data.frame(time= auc_cox[["AUC"]][["score"]][["times"]],
             AUC=auc_cox[["AUC"]][["score"]][["AUC"]])
auc_train_tab`

![image](https://github.com/drizopoulos/JMbayes2/assets/74847937/f47f685f-c4da-4daa-b673-bb16bf4f046c)

Dynamic joint model and calculate AUC values from 1 year to 5 years
`
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
fm1 <- lme(log(serBilir) ~ ns(year, 3) * sex, data = pbc2,
           random = ~ ns(year, 3) | id, control = lmeControl(opt = 'optim'))

fm2 <- lme(prothrombin ~ ns(year, 2) * sex, data = pbc2,
           random = ~ ns(year, 2) | id, control = lmeControl(opt = 'optim'))

fm3 <- mixed_model(ascites ~ year * sex, data = pbc2,
                   random = ~ year | id, family = binomial())
CoxFit <- coxph(Surv(years, event) ~ drug + age, data = pbc2.id)
jointFit <- jm(CoxFit, list(fm1, fm2, fm3), time_var = "year")

pbc2$event <- as.numeric(pbc2$status != "alive")
roc1 <- tvROC(jointFit, newdata = pbc2, Tstart = 0, Dt = 1)
roc2 <- tvROC(jointFit, newdata = pbc2, Tstart = 0, Dt = 2)
roc3 <- tvROC(jointFit, newdata = pbc2, Tstart = 0, Dt = 3)
roc4 <- tvROC(jointFit, newdata = pbc2, Tstart = 0, Dt = 4)
roc5 <- tvROC(jointFit, newdata = pbc2, Tstart = 0, Dt = 5)

tvAUC(roc1)
tvAUC(roc2)
tvAUC(roc3)
tvAUC(roc4)
tvAUC(roc5)`

![image](https://github.com/drizopoulos/JMbayes2/assets/74847937/874005f3-4deb-4869-aa3a-6bfb72585339)

![image](https://github.com/drizopoulos/JMbayes2/assets/74847937/2345395d-ed17-4fdc-8866-eb38dac2a044)

**Comment by drizopoulos** [comment]
Are you certain you compare the same AUCs? In the survival analysis setting, there are different definitions of the AUC.
