### ISSUE TITLE
non-linear mixed models for longitudinal data?

### ISSUE THREAD

**Issue by danielinteractive** [drizopoulos/JMbayes2#8]
Hi Dimitris and team,

first of all thanks for sharing this nice package with the community - the interface looks really elegant and flexible!

One question: We are often interested in fitting parametric non-linear models for the longitudinal data (reasons are better interpretability, extrapolation, etc.) - any chance that the `nlme()` function could be used too in the end in `JMbayes2` and not just `lme()`?

Thanks for your thoughts,
cheers
Daniel

**Comment by drizopoulos** [comment]
Hi Daniel,

Unfortunately, this is not in our immediate plans.

Best,
Dimitris


——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
From: Daniel Sabanes Bove ***@***.***>
Sent: Thursday, November 18, 2021 9:13:12 PM
To: drizopoulos/JMbayes2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/JMbayes2] non-linear mixed models for longitudinal data? (Issue #8)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Dimitris and team,

first of all thanks for sharing this nice package with the community - the interface looks really elegant and flexible!

One question: We are often interested in fitting parametric non-linear models for the longitudinal data (reasons are better interpretability, extrapolation, etc.) - any chance that the nlme() function could be used too in the end in JMbayes2 and not just lme()?

Thanks for your thoughts,
cheers
Daniel
