### ISSUE TITLE
Prediction of survival probabilities

### ISSUE THREAD

**Issue by berithunsdieck** [drizopoulos/JMbayes2#81]
Lets assume I have a survival model surv_model and a joint model joint_mod, where the surv_model is given as input. Shouldn't the prediction of the risks using the joint model be at least as good as the prediction of the risks using only the survival model?

For predicting these I use this code: 

```
# for base survival model:
surv_probs <- pec::predictSurvProb(surv_model, newdata=input_survival_data,times=t0+12)

# for joint model: 
predSurv <- predict(model_of_interest, 
                    newdata = long_data%>%mutate(status2=0,total_months=t0), 
                    process = "event",
                    times = t0+12,
                    return_newdata = TRUE,type="subject_specific")
```

but looking e.g. at the AUC/ROC-curve, the prediction is way worse than the one using the survival model. How can I improve it? Am I using the right funtions for predicting resp. comparing?

**Comment by berithunsdieck** [comment]
@drizopoulos  The code of the package is used for generating the joint model. Shouldn't the joint model be at least as good as the survival model you put in for fitting the joint model?

**Comment by drizopoulos** [comment]
Not if the longitudinal outcome is not a good predictor of the survival outcome.

**Comment by berithunsdieck** [comment]
But shouldn't then be the estimate of the longitudinal outcome be set to 0?

**Comment by drizopoulos** [comment]
The new version should resolve this.
