### ISSUE TITLE
Compare Cox and dynamic prediction model

### ISSUE THREAD

**Issue by bbb801** [drizopoulos/JMbayes2#82]
Dear Sir/Madam,

I have constructed a Cox model using coxph() and dynamic prediction model using the cox and lme() now. How can I compare the performances between the cox and the dynamic prediction models? How do I know the dynamic prediction model is better than the Cox model? Which package, function or metric can I use? Sorry for the stupid question.

Regards,
Jundong

**Comment by drizopoulos** [comment]
This is a theoretical question for which you need to search the literature. It does not relate to a coding issue with the package.

**Comment by bbb801** [comment]
Thank you. May I know if the package provides function(s) to compare Cox and the dynamic prediction model? I failed to involve the Cox in tvROC.
