### ISSUE TITLE
tvROC for Cox

### ISSUE THREAD

**Issue by bbb801** [drizopoulos/JMbayes2#83]
Dear Sir,

It seems tvROC can not be used for Cox model. Is there a way to revise it for Cox?
![image](https://github.com/drizopoulos/JMbayes2/assets/52306405/fb894cc6-e978-4b46-a969-48d5b053cf59)

**Comment by drizopoulos** [comment]
Yes, `tvROC()` is not designed to work with Cox models. You could adapt to work with the landmark approach that required fitting a series of Cox models at different follow-up times, but that would require changing the underlying code.
