### ISSUE TITLE
no events in the interval [Tstart, Thoriz)

### ISSUE THREAD

**Issue by bbb801** [drizopoulos/JMbayes2#84]
Dear Sir,

I am using tvROC to compute AUC in the testing set with the model trained in the training set . However, I encountered an error when I set Tstart = 0 (Dt=8). It said 'it seems that there are no events in the interval [Tstart, Thoriz)'.  When I set Tstart = 3 (Dt=5) or Tstart = 3 (Dt=8), it had no error. It is weird that  no events in the interval [Tstart=0, Thoriz=0+8), while it had events in the interval [Tstart=3, Thoriz=3+5). Moreover, it seems that Tstart = 0 always results in an error in an data. Any suggestion? My minimun follow-up time is 0 and minimun survival time is 0.03285.

![image](https://github.com/drizopoulos/JMbayes2/assets/52306405/a5e96b00-bd60-479e-bb44-29e3ab20dee5)

**Comment by drizopoulos** [comment]
For the subjects who have an event in the interval (`Tstart`, `Tstart + Dt`), you should check if they have any longitudinal measurements at and before `Tstart`. Also, you could try setting `Tstart = 0.0001`.

**Comment by bbb801** [comment]
Should all first longitudinal measurements be at and before Tstart? It seems most of my first longitudinal measurements are after the admission date.

**Comment by drizopoulos** [comment]
Yes, you need to have longitudinal data before `Tstart`.

**Comment by bbb801** [comment]
Thank you. My baseline date is the hospital admission. Longitudinal data is the lab test events. What if the first lab tests are normally over the admission date? If it is still workable to use your model?

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Dimitris Rizopoulos ***@***.***>
Sent: Thursday, February 22, 2024 4:51:04 PM
To: drizopoulos/JMbayes2 ***@***.***>
Cc: LIU Jundong ***@***.***>; Author ***@***.***>
Subject: [Ext] Re: [drizopoulos/JMbayes2] no events in the interval [Tstart, Thoriz) (Issue #84)

CAUTION: External email. Do not reply, click on links or open attachments unless you recognize the sender and know the content is safe.


Yes, you need to have longitudinal data before Tstart.

―
