### ISSUE TITLE
Predicting outside of follow-up time

### ISSUE THREAD

**Issue by PieterVeere** [drizopoulos/JMbayes2#85]
First of, thank you for building this great package! I would like to use it to run simulations based on my data containing a cognitive functioning outcome (continuous) and a indicator of cognitive state change (time-to-event, binary). Now I run into trouble when I want to predict events outside of my datarange. There are two possible approaches I tried: 

1. I cannot work out how to extract the baseline hazard the joint model generates. Based on the github code it seems to always use a spline for the baseline hazard, but I cannot figure out how to extract the information. Within the joint-model-object under $statistics the bs_gammas seem to relate to the spline over the baseline hazard, but I don't know to determine the baseline hazard from the provided information. With the spline equation I could try to generate the survival probabilities myself.
2. The predict.jm function does not seem to give a prediction outside of the maximum datarange of the data used to built the model. For stackoverflow I made a little example which I included below.

As a sidenote: I would prefer for the joint model to use some parametric baseline hazard distribution, but even when I specify a weibull distribution in the input survival model, JMbayes2 seems to generate a spline. 

Example based on example code provided alongside the JMbayes2 package:

library(JMbayes2)
library(dplyr)
pbc2$years %>% max ##maximum follow-up is 14.3 yhears
pbc2.id$status2 <- as.numeric(pbc2.id$status != 'alive')
SurvFit <- survreg(Surv(years, status2) ~ sex, data = pbc2.id, dist = "weibull")
fm1 <- lme(log(serBilir) ~ ns(year, 3) * sex, data = pbc2,
           random = ~ ns(year, 3) | id, control = lmeControl(opt = 'optim'))

jointFit <- jm(CoxFit, fm1, time_var = "year")

##Selecting patients from the pbc data for which I want a prediction
t0 <- 3
ND <- pbc2[pbc2$id %in% c(2, 25), ]
ND <- ND[ND$year < t0, ]
ND$status2 <- 0
ND$years <- t0

#predictions for the longitudinal outcomes using newdata
predLong1 <- predict(jointFit, newdata = ND, return_newdata = TRUE
                     , process = "event"
                     , times = 14:15 ##one datapoint before the maximum follow-up, one after
                     )
predLong1 %>% dplyr::select(id, year, pred_CIF)
With predLong1 showing this output not including the 15th year of requested follow-up:

id year  pred_CIF
6      2    3 0.0000000
6.1    2   14 0.5943413
171   25    3 0.0000000
171.1 25   14 0.2668998

**Comment by drizopoulos** [comment]
Indeed, currently, the only option is a penalized B-spline for the logarithm of the baseline hazard. Because this is a semi-parametric estimation approach, you cannot extrapolate beyond the maximum follow-up time. This can only be done with a parametric model like the Weibull. 

The `bs.gammas` are the coefficients for the estimated coefficients for the baseline hazard. From the returned object, you can extract the knots used in the calculation from `object$control`. However, as mentioned above, you can still not stably extrapolate.
