### ISSUE TITLE
Question about JMBayes2

### ISSUE THREAD

**Issue by MinzeeKim** [drizopoulos/JMbayes2#87]
Hi Dr. Rizopoulos,

Thank you for a great package. I have a couple of questions about JMBayes2:

- How does this packing fit the Bayesian model in `jm()`? Is it using rstan or JAGS?
- Do you have documentation published about the package (for example, something similar to "The R Package JMbayes for Fitting Joint Models for Longitudinal and Time-to-Event Data Using MCMC" published in the Journal of Statistical Software)? This documentation has been very detailed and helpful, so I was wondering if you have something similar for the JMBayes2 package or if I can refer to this documentation for JMBayes2 as well. 

Thank you so much!

**Comment by drizopoulos** [comment]
JMbayes2 uses a custom-made MCMC code written in C++.

We are currently writing a paper to showcase the capabilities of the package. In the meantime, a lot of information is provided in the website: [https://drizopoulos.github.io/JMbayes2/](https://drizopoulos.github.io/JMbayes2/).
