### ISSUE TITLE
unit in association with area using jm() and area()

### ISSUE THREAD

**Issue by ahulman** [drizopoulos/JMbayes2#88]
Hi Dimitris.
We are using the package to examine the association between HbA1c trajectories (interested in value, slope, area assoc.) and kidney-related outcomes. We noticed that the HR for area is surprisingly high, around 1.40, which makes us wonder what the unit is. We thought that 1 area unit (year x % [% refers to the unit of HbA1c and not any relative measure]) is basically having a 1 unit higher HbA1c over 1 year, but then the estimates quickly explode i.e. someone who has just 1 unit higher HbA1c (which is not that much) over a 10 year period would have almost 30-fold risk, which is not realistic at all clinically. Are we misinterpreting something? We did a sanity check using a Cox regression, where we calculated the area under the HbA1c trajectories (trapezoid rule) manually and used that as a variable in the Cox model. We excluded people who had the event or were censored before year 5, and subtracted 5 from the follow-up time. This model gives a HR of 1.06, which makes more clinical sense, which also makes us think that we are overlooking sg with the JM. 

Unfortunately, we cannot share the data, but I thought you might have a thought without that. Otherwise, I will try to simulate a reproducible example. A bit about the dataset. n~5000 Median (Q1, Q3) follow up time is around 10 (5,15) years, approx 10-15% has the outcome.  
We appreciate your time and any thoughts on this.

**Comment by drizopoulos** [comment]
For better interpretability reasons, `area()` calculates the area under the trajectory between $(0, t)$ divided by $t$; see also here: [https://drizopoulos.github.io/JMbayes2/articles/JMbayes2.html#functional-forms](https://drizopoulos.github.io/JMbayes2/articles/JMbayes2.html#functional-forms).

**Comment by drizopoulos** [comment]
In my view, this is exactly the reason why the normalized area is easier to interpret. Namely, the value of the area depends on the specific $t$ we are speaking about. The normalized area has the interpretation of the average biomarker level from the beginning of the follow-up up to $t$.
