### ISSUE TITLE
AUC too low compared to standard risk equations

### ISSUE THREAD

**Issue by hollypavey22** [drizopoulos/JMbayes2#90]
I have run a joint model analysis of  repeated measure biomarker and adjusted for the established cardiovascular risk factors. I am performing CV risk prediction. For all established risk models, the AUC is around 0.7. If I use my data with the standard cardiovascular risk factors (without the repeat measurements biomarker) I also get a AUC of 0.65 which is realistic. 

I have used the predict function (JMbayes2) to estimate the AUC and the tvAUC (JMbayes2), the AUC is around 0.53. 

It does not make sense that after adding a repeat biomarker, the AUC is lower than using the survival model alone without repeat measurements.  

Why is the AUC so much lower using the predictions from the joint model compared to a standard survival model?

**Comment by drizopoulos** [comment]
There are different versions of AUC for survival data. It is unclear whether you compare the AUC under the same definition. Also, there are different ways to account for censoring. Likewise, it is unclear if the method to correct for censoring is the same in the numbers reported. What is done in JMbayes2 is described in Section 6.4 [here](https://www.drizopoulos.com/courses/EMC/ESP72.pdf).

**Comment by hollypavey22** [comment]
Thnak you for the response. 
However, I also used the predict function in JMbayes2 to estimate the survival probabilites and then i could manually calculate the AUC the same way as I did with a standard cox model. 
Here, the AUC was still very much lower, so it seems the conflict is in the survival probabilites from the predict command?

**Comment by drizopoulos** [comment]
The `predict()` function calculates conditional cumulative risk probabilities. That is, the probability of getting an event after the time of the last longitudinal measurement. From a Cox model you typically get marginal cumulative risk probabilities. These two are not  the same.

**Comment by drizopoulos** [comment]
The new version should resolve this.
