### ISSUE TITLE
https://drizopoulos.github.io/JMbayes2/articles/Recurring_Events.html   jm_fit 

### ISSUE THREAD

**Issue by nkchangshu** [drizopoulos/JMbayes2#91]
#organize the failure-time data in the counting process formulation
library(JMbayes2)
cox_data <- rc_setup(rc_data = recu_data, trm_data = term_data,
                     idVar = "id", statusVar = "status",
                     startVar = "tstart", stopVar = "tstop",
                     trm_censLevel = 0,
                     nameStrata = "strata", nameStatus = "status")
cox_data[cox_data$id == 1, c("id", "tstart", "tstop", "status", "strata")]

#Fitting the model
#fit the linear mixed model that describes the longitudinal outcome
lme_fit <- lme(y ~ ns(time, k =  c(1, 3), B = c(0, 7)), 
               random = list(id = pdDiag(form = ~ ns(time, k = c(1, 3), 
                                                     B = c(0, 7)))),
               data = lme_data,
               control = lmeControl(opt = "optim", niterEM = 45))
#fit a stratified Cox model using the transformed data
cox_fit <- coxph(Surv(tstart, tstop, status) ~ (group + age) : strata(strata),
                 data = cox_data)
#
jm_fit <- jm(cox_fit, lme_fit, time_var = "time", recurrent = "gap",
             functional_forms =  ~ value(y) : strata)
I've been smoothly running my code and have constructed the necessary datasets without any issues up to the point of using the jm function from the JMbayes2 package. However, when I execute the following line: jm_fit <- jm(cox_fit, lme_fit, time_var = "time", recurrent = "gap",
             functional_forms = ~ value(y) : strata)
I encounter the error: Error in `colnames<-`(`*tmp*`, value = paste0("D[", row(initial_values$D)[ind], : cannot set 'colnames' on an object with less than two dimensions
R version: 4.2.3
JMbayes2 version: 0.4-99
How can I resolve this issue? Thank you very much!

**Comment by drizopoulos** [comment]
It should be resolved in the current development version on GitHub.
