### ISSUE TITLE
Setting initial values  on jm function

### ISSUE THREAD

**Issue by camposacrs** [drizopoulos/JMbayes2#92]
hello,
I want to test the stability of joint model estimation  introducing small noises on the set of initial values for the model parameters. 
I could see that the jm object returns the default vector of initial values, but I couldn`t find an argument where I can propose mine. 
Is it available in the current verson of JMBayes2?
Thanks,
Aline

**Comment by drizopoulos** [comment]
Indeed, have not yet allowed for user-specified initial values. We plan to do this in a future version. However, note that `jm()` by default jitters the initial values for each chain of the MCMC, i.e., see [here](https://github.com/drizopoulos/JMbayes2/blob/b4e308cc62d965f01ffeb64f0c63c4846c41896e/R/jm_fit.R#L101).
