### ISSUE TITLE
References for fit statistics computation

### ISSUE THREAD

**Issue by JulietteOrtholand** [drizopoulos/JMbayes2#93]
Thank you very much for your very nice package. I have been using the different fit statistics output by the model (WAIC, DIC, LPML) but I was not able to find the reference of the computations of your package. As different updated versions of these scores exist, I was wondering if you could please indicate to me which one you are using. 

Many thanks in advance for your time and your help,

Juliette

**Comment by drizopoulos** [comment]
These statistics are calculated by the internal function `JMbayes2:::fit_stats` in which `lL` denotes the log-likelihood. For the conditional version of these statistics, `lL` is the log-likelihood conditional on the random effects. For the marginal version, the random effects are integrated out using the Laplace approximation.

**Comment by JulietteOrtholand** [comment]
Thank you for your answer. I am sorry I might have not been precise enough with my question. I was wondering about the literature reference you are using for the computations, I wanted to confirm the following:

- WAIC: [Watanabe, Sumio, "Asymptotic Equivalence of Bayes Cross Validation and Widely Applicable Information Criterion in Singular Learning Theory", (2010), Journal of Machine Learning Research]

- DIC: [Spiegelhalter, David J.; Best, Nicola G.; Carlin, Bradley P.; van der Linde, Angelika (2002). "Bayesian measures of model complexity and fit (with discussion)". Journal of the Royal Statistical Society, Series B] which seems to be the same version as the one of [Gelman, Andrew; Carlin, John B.; Stern, Hal S.; Rubin, Donald B. (2004). Bayesian Data Analysis: Second Edition.],

- LPML: [Ibrahim JG, Chen M-H, Sinha D. (2001) Bayesian Survival Analysis. Springer-Verlag]

**Comment by drizopoulos** [comment]
If I recall correctly, I have used this [reference](https://stat.columbia.edu/~gelman/research/published/waic_understand3.pdf).
