### ISSUE TITLE
functional_forms argument and random effects association 

### ISSUE THREAD

**Issue by hortensedoms** [drizopoulos/JMbayes2#95]
With JMbayes it was possible to define a random effects association using the following argument : param="shared-RE" .
How can we do this with JMbayes2 using the functional_forms argument?

Also, what does the function coefs(x, zero_ind = NULL) do in the argument "functional_forms" ? What type of association is linked to this function ? 

Thank you very much

**Comment by drizopoulos** [comment]
The option `shared-RE` is not currently supported in **JMbayes2**.

The `coefs()` function can be used to set the columns of the design matrix to zero. For instance, if you fit a model as `y ~ time + sex`, and you use `functional_forms = ~ coefs(y, zero_ind = c(1, 3))`, it will only include the $(\beta_1 + b_{i1})t$ in the linear predictor of the survival submodel.
