### ISSUE TITLE
Different results by re-arranging data

### ISSUE THREAD

**Issue by berithunsdieck** [drizopoulos/JMbayes2#96]
I simulated a data example where one biomarker impacts the diagnosis over time directly. If I use a simple lme model as longitudinal model, the effect is not given in the joint model, only after rearranging the longitudinal data by 
`long_data2 <- long_data%>%group_by(SID)%>%slice(1:n())%>%ungroup()` 
 the biomarker is significant and the results look completely different.
Can you explain why this is the case? 
Additionally, if the data is not given by long_data2, it is not possible to predict on it (incompatible dimensions).

**Comment by drizopoulos** [comment]
Can you send a reproducible example?



I simulated a data example where one biomarker impacts the diagnosis over time directly. If I use a simple lme model as longitudinal model, the effect is not given in the joint model, only after rearranging the longitudinal data by
long_data2 <- long_data%>%group_by(SID)%>%slice(1:n())%>%ungroup()
the biomarker is significant and the results look completely different.
Can you explain why this is the case?
Additionally, if the data is not given by long_data2, it is not possible to predict on it (incompatible dimensions).
