### ISSUE TITLE
Inconsistent event predictions for competing risk model

### ISSUE THREAD

**Issue by jonathanhori** [drizopoulos/JMbayes2#97]
I am experiencing issues when making and evaluating event predictions using a joint model with competing risks. I am not sure to what extent these issues are related. Any advice you are able to provide on why this might be occurring would be greatly appreciated.

- First, I find that I obtain different event predictions when the subjects contained in the `newdata` provided to `predict()` differ. For example, when I have a test set of subjects to make dynamic event predictions, I can obtain different event predictions when 1) providing each patient individually as the `newdata`, versus 2) when disjoint groups of subjects are provided as the `newdata`, versus 3) when the entire test set is provided as the `newdata`. In my case, my model does not appear to have convergence issues, as indicated by Rhat values below 1.1 as previously suggested.
- The quality of these inconsistent predictions obtained above varies when evaluating cumulative-dynamic time-dependent AUC. If I provide the entire test set as the `newdata`, the dynamic predictions I obtain consistently have very low AUCs, of around 0.5. However, for the exact same subjects provided group-by-group as the `newdata`, I can obtain predictions with AUCs close to 0.7-0.8.
- Often, it appears that subjects are skipped when the entire test set is provided together as `newdata`. In some cases, I see that 13% of the subjects I provide do not have any predictions returned. If I feed these skipped subjects back into `predict()` as the `newdata`, I can obtain predictions for some of these subjects, but still most of these subjects are skipped again.
- I obtain the below error when making predictions for one subject at a time (which occurs in my example below). At a glance, it does not appear due to missing biomarker values. 

```
Error: Col::rows(): indices out of bounds or incorrectly used

6. stop(structure(list(message = "Col::rows(): indices out of bounds or incorrectly used",
call = NULL, cppstack = NULL), class = c("std::out_of_range",
"C++Error", "error", "condition")))

5. simulate_REs(Data, mcmc, control)

4. sample_parallel(id_samples[[1L]], Data = Data, mcmc = mcmc, control = control)

3. get_components_newdata(object, newdata, con$n_samples, con$n_mcmc,
con$parallel, con$cores, con$seed, con$use_Y)

2. predict.jm(jm_fit, newdata = list(newdataL = newdata$newdataL %>%
filter(id %in% c(subj_id)), newdataE = newdata$newdataE %>%
filter(id %in% c(subj_id))), times = hor, return_newdata = TRUE,
process = "event")

1. predict(jm_fit, newdata = list(newdataL = newdata$newdataL %>%
filter(id %in% c(subj_id)), newdataE = newdata$newdataE %>%
filter(id %in% c(subj_id))), times = hor, return_newdata = TRUE,
process = "event")
```

I have attempted to provide an example that reproduces the issue of inconsistent predictions when subjects are provided one-at-a-time versus all together. Note that this is not entirely analogous, as my model here does appear to have some Rhat values above 1.1.

I am using R version 4.2.1 and JMbayes2 version 0.5-0.

```
# load packages 
library(tidyverse)
library(JMbayes2)
```

```
# setup train/test split
pbc2.id %>% head
pbc2 %>% head

pbc2 <- pbc2 %>% 
  group_by(id) %>% 
  mutate(num_serchol = sum(!is.na(serChol))) %>% 
  ungroup()

FILTER <- FALSE
if (FILTER) {
  pbc2 <- pbc2 %>% 
    filter(num_serchol > 0)
  pbc2.id <- pbc2.id %>% 
    filter(id %in% pbc2$id)
} else {
  pbc2.id <- pbc2.id
}


set.seed(123)

ids <- pbc2.id %>% distinct(id)

test_ids <- ids %>% 
  slice_sample(prop = 0.2)

training.id <- pbc2.id %>% 
  filter(!(id %in% test_ids$id))
training <- pbc2 %>% 
  filter(!(id %in% test_ids$id))

test.id <- pbc2.id %>% 
  filter(id %in% test_ids$id)
test <- pbc2 %>% 
  filter(id %in% test_ids$id)

training.idCR <- crisk_setup(training.id, statusVar = "status", 
                             censLevel = "alive",
                             nameStrata = "CR",
                             nameStatus = "status_indicator")

test.idCR <- crisk_setup(test.id, statusVar = "status", 
                             censLevel = "alive",
                             nameStrata = "CR",
                             nameStatus = "status_indicator")
```

```
# Setup submodels

cox_fit <- coxph(Surv(years, status_indicator) ~ 
                   (age + sex + histologic) * strata(CR),
                 data = training.idCR)

ctrl <- lmeControl(opt = 'optim')
lm_chol <- lme(log(serChol) ~ year * (age + sex),
              data = training,
              random = ~ 1 + year | id,
              control = ctrl, method = "ML",
              na.action = na.exclude)

lm_pro <- lme(prothrombin ~ year * (age + sex),
              data = training,
              random = ~ 1 + year | id,
              control = ctrl, method = "ML",
              na.action = na.exclude)
```

```
# Fit JM

fform_withslope <- list(
  "log(serChol)" = 
    ~ value(log(serChol)):CR + slope(log(serChol)):CR,
  "prothrombin" = 
    ~ value(prothrombin):CR + slope(prothrombin):CR
)

jm_fit <- jm(cox_fit, 
             list(lm_chol, lm_pro),
             time_var = "year",
             functional_forms = fform_withslope,
             # n_iter = 25000L, n_burnin = 5000L, n_thin = 5L
             n_iter = 50000L, n_burnin = 10000L, n_thin = 5L
             )
```

```
# Make predictions

t <- 2
hor <- 10


newdata <- list(
  newdataL = test %>% 
    filter(year < t),
  newdataE = test.idCR %>% 
    mutate(status_indicator = 0,
           years = t
           )
)

# error occurs below
return_frame <- data.frame()
for (subj_id in test_ids$id) {
  print(subj_id)
  predEvent1 <- predict(jm_fit,
                       newdata = 
                         list(
                           newdataL = newdata$newdataL %>% 
                             filter(id %in% c(subj_id)),
                           newdataE = newdata$newdataE %>% 
                             filter(id %in% c(subj_id))
                         ),
                       times = hor,
                       return_newdata = TRUE,
                       process = "event"
                       )
  
  p1 <- predEvent1 %>%
    filter(years == hor) %>%
    select(id, "_strata", contains("CIF")) %>% 
    rename(strata = `_strata`) %>% 
    print()
  
  return_frame <- bind_rows(return_frame, p1)
  
}


predEvent2 <- predict(jm_fit.pval, #jm_fit,
                     newdata = 
                       newdata,
                     times = hor,
                     return_newdata = TRUE,
                     process = "event"
                     )

p2 <- predEvent2 %>%
  filter(years == hor) %>%
  select(id, "_strata", contains("CIF")) %>% 
  rename(strata = `_strata`) %>% 
  print()


return_frame %>% 
  inner_join(p2, by = c("id", "strata")) %>% 
  select(id, strata, contains("pred_CIF")) %>% 
  filter(strata == "transplanted") %>% 
  ggplot() +
  geom_point(aes(x = pred_CIF.x, y = pred_CIF.y))
```

**Comment by drizopoulos** [comment]
The `predict()` method calculates predictions using a Monte Carlo scheme. This inherently causes the issue you observed with different predictions for the same subject. You can stabilize the predictions by increasing the number of Monte Carlo samples, i.e., the `n_samples` control argument of `predict()`.

The error that occurs for Subject 41 is because at t = 2 both of her serum cholesterol measurements are zero. The current implementation requires at least one longitudinal measurement per outcome. I'll see how to change the underlying code to allow situations like this one where all the measurements of a longitudinal outcome are missing.
